/* ----------------------------- UI / panels ------------------------------ */
currentObjective=function(){if(S.champion)return 'CHAMPION · Explore Asterra freely';const area=classicArea();if(S.currentArea==='seabreeze'&&!S.storyFlags.lab)return 'NEXT · Professor Linden’s Lab';if(area.gym&&!S.badges[area.gym]&&badgeCount()===GYMS[area.gym].index-1)return `NEXT · ${GYMS[area.gym].type} Gym · earn Badge ${GYMS[area.gym].index}`;if(S.currentArea==='league')return badgeCount()<8?`Need ${8-badgeCount()} more Gym Badge${8-badgeCount()===1?'':'s'}`:'NEXT · Enter the Elite Four';const gate=currentMap?.objects.find(o=>o.type==='hmGate');if(gate)return `FIELD MOVE · ${gate.hm} blocks the route`;const door=currentMap?.objects.find(o=>o.type==='puzzleDoor');if(door)return 'CAVE PUZZLE · Activate all three switches';if(area.next)return `NEXT · ${CLASSIC_AREAS[area.next].name}`;return area.objective||'Explore Asterra'};
function classicMissionPlan(){const n=badgeCount(),nextGym=Object.entries(GYMS).find(([,g])=>g.index===n+1);const nextTown=nextGym?Object.entries(CLASSIC_AREAS).find(([,a])=>a.gym===nextGym[0])?.[1]:null;return `<div class="planTitle"><span>GYM CHALLENGE</span><small>${n}/8 BADGES</small></div>${planRow(1,'Explore routes and towns',classicArea().name,{done:n>0,current:n===0})}${planRow(2,nextGym?`Reach ${nextTown?.name||'the next Gym'}`:'Enter Victory Road',nextGym?`${nextGym[1].type} Gym · Badge ${nextGym[1].index}`:'All eight Badges earned',{current:!!nextGym,done:!nextGym})}${planRow(3,'Train and collect TMs','Wild levels and BST scale with your Badges',{current:true})}${planRow(4,'Pokémon League',S.champion?'Champion crowned':'Elite Four + Champion',{done:S.champion,current:n>=8&&!S.champion,locked:n<8})}`}
updateSideUI=function(){if(!S.started)return;const area=classicArea(),n=badgeCount(),lead=S.party[0];DOM.titanName.textContent=area.name;DOM.titanSubtitle.textContent=area.subtitle;DOM.cycleOrb.textContent=n;DOM.cycleText.textContent=`${n} / 8 BADGES`;DOM.campaignProgressLabel.textContent=`GYM CHALLENGE · ${n}/8`;DOM.resonancePips.innerHTML=Array.from({length:8},(_,i)=>`<i class="${i<n?'on':''}"></i>`).join('');DOM.questTitle.textContent=S.champion?'Asterra Champion':currentObjective();DOM.questDescription.textContent=area.objective||`${area.kind==='town'?'Restock, heal, talk to trainers, and challenge the Gym when ready.':'Wild Pokémon only roam inside tall-grass patches. Trainers and hidden items reward exploration.'}`;DOM.questProgressBar.style.width=`${n/8*100}%`;DOM.questProgressText.textContent=`${n}/8 BADGES · BST CAP ${bstCap()} · ${levelRange(area).join('–')} WILD LEVELS`;DOM.fieldCredits.textContent=`₽ ${S.fieldCredits}`;DOM.bondLabel.textContent=gymStatusName();DOM.bondBar.style.width=`${n/8*100}%`;DOM.bondReaction.textContent=n<8?`Next milestone: Badge ${n+1}. HMs unlock permanent field traversal.`:'Victory Road and the Pokémon League are open.';if(lead)DOM.leadCard.innerHTML=`<div class="leadMon"><img src="${spritePath(lead.species)}"><div><h3>${escapeHtml(lead.name)}</h3><div class="leadMeta"><b>Lv.${lead.level}</b>${typePills(lead.types)}</div><div class="miniHp"><i style="width:${lead.hp/lead.maxHp*100}%"></i></div><div class="leadMeta">${lead.hp} / ${lead.maxHp} HP</div></div></div>`;const pool=classicEncounterPool(area).slice(0,3);DOM.ecosystemPulse.innerHTML=pool.length?pool.map(id=>`<div class="pulseRow"><img src="${spritePath(id)}"><div><div class="pulseName">${SPECIES[id].name}</div><div class="pulseTrend">Tall grass · BST ${classicBST(id)}</div></div><b>Lv.${levelRange(area)[0]}+</b></div>`).join(''):'<div class="pulseRow"><div><div class="pulseName">Safe settlement</div><div class="pulseTrend">No wild Pokémon inside town limits</div></div></div>';DOM.migrationTicker.textContent=S.lastTicker||`${area.name} · ${area.subtitle}`;DOM.objectiveChip.textContent=currentObjective();if(DOM.missionPlan)DOM.missionPlan.innerHTML=classicMissionPlan();DOM.tutorialCard?.classList.add('hidden')};
renderMissionPlan=function(){if(DOM.missionPlan)DOM.missionPlan.innerHTML=classicMissionPlan()};updateTutorialUI=function(){DOM.tutorialCard?.classList.add('hidden')};
renderWorld=function(time=0){requestAnimationFrame(renderWorld);if(!S.started||!currentMap||DOM.gameApp.classList.contains('hidden'))return;processHeldMovement(time);WORLD3D.render(time,{state:S,map:currentMap,titan:classicVisual(),wilds:wildVisuals})};
showAreaBanner=function(title=null,subtitle=null){const area=classicArea();DOM.areaBanner.innerHTML=`${title||area.name}<small>${(subtitle||area.subtitle).toUpperCase()}</small>`;DOM.areaBanner.classList.remove('hidden');void DOM.areaBanner.offsetWidth;setTimeout(()=>DOM.areaBanner.classList.add('hidden'),2600)};

openAtlasPanel=function(){const cards=CLASSIC_AREA_ORDER.map((id,i)=>{const a=CLASSIC_AREAS[id],visited=!!S.visitedAreas[id],current=id===S.currentArea,gym=a.gym?GYMS[a.gym]:null;return `<button class="regionMapNode ${current?'current':''}" data-map-area="${id}" ${visited?'':'disabled'}><b>${i+1}. ${a.name}</b><small>${a.subtitle}</small><em>${gym?S.badges[a.gym]?`✓ ${gym.badge}`:`GYM ${gym.index} · ${gym.type}`:a.kind.toUpperCase()}</em></button>`}).join('');openPanelHtml(panelShell('TOWN MAP',`${CLASSIC_REGION_NAME} Region`,canUseHM('Fly')?'HM Fly is active: visited towns can be selected for fast travel.':'Explore routes to reveal them. HM Fly later enables fast travel.',`<div class="regionMapGrid">${cards}</div>`),{type:'atlas'});$$('[data-map-area]',DOM.panelCard).forEach(btn=>btn.onclick=()=>{const id=btn.dataset.mapArea,a=CLASSIC_AREAS[id];if(canUseHM('Fly')&&S.visitedTowns[id]&&id!==S.currentArea){closePanel();enterClassicArea(id,{announce:true});toast(`${S.party.find(m=>knowsMove(m,'fly'))?.name||'Your Pokémon'} used Fly.`)}else toast(`${a.name} · ${a.subtitle}`)})};
openFieldNotesPanel=function(){const seen=Object.keys(S.research||{}),caught=Object.keys(S.catches||{}).filter(id=>S.catches[id]>0),rows=Object.keys(SPECIES).sort((a,b)=>SPECIES[a].name.localeCompare(SPECIES[b].name)).map(id=>{const known=seen.includes(id)||caught.includes(id),capt=S.catches[id]||0;return `<tr><td><div class="fieldSpecies"><img src="${known?spritePath(id):'assets/shop/items/poke-ball.png'}"><span>${known?SPECIES[id].name:'????'}</span></div></td><td>${known?SPECIES[id].types.join('/'):'—'}</td><td>${known?classicBST(id):'—'}</td><td>${capt}</td></tr>`}).join('');openPanelHtml(panelShell('POKÉDEX','Asterra Field Dex',`${seen.length} studied · ${caught.length} caught.`,`<table class="fieldTable"><thead><tr><th>Species</th><th>Type</th><th>BST</th><th>Caught</th></tr></thead><tbody>${rows}</tbody></table>`),{type:'fieldnotes'})};
openMonInspect=function(mon,back=null){const stats=[['HP',`${mon.hp} / ${mon.maxHp}`],['Attack',mon.atk],['Defense',mon.def],['Sp. Attack',mon.spa],['Sp. Defense',mon.spd],['Speed',mon.spe],['Experience',`${mon.xp} / ${xpNeeded(mon)}`],['Origin',mon.starter?'Seabreeze partner':CLASSIC_AREAS[mon.caughtAt]?.name||'Asterra']];const moves=mon.moves.map(mm=>{const m=MOVES[mm.id];return `<div class="moveLine" style="--move-color:${TYPE_COLORS[m.type]}"><b>${m.name}</b><small>${m.type} · ${m.category} · Power ${m.power||'—'} · PP ${mm.pp}/${mm.maxPp}</small></div>`}).join('');openPanelHtml(panelShell('POKÉMON SUMMARY',mon.name,`${mon.types.join(' / ')} · Level ${mon.level}`,`<div class="inspectLayout"><div class="inspectArt"><img src="${spritePath(mon.species)}"></div><div class="inspectStats"><h3>${escapeHtml(mon.name)}</h3><div class="statRows">${stats.map(([a,b])=>`<div class="statRow">${a}<b>${b}</b></div>`).join('')}</div><div class="moveList">${moves}</div></div></div>`),{type:'inspect'});$('.closePanel',DOM.panelCard).onclick=()=>back?back():closePanel()};
openPartyPanel=function(){const cards=S.party.map((m,i)=>`<article class="partyCard ${i===0?'lead':''}"><img src="${spritePath(m.species)}"><div><h3>${escapeHtml(m.name)}</h3><p>Lv.${m.level} · ${m.hp}/${m.maxHp} HP</p><div>${typePills(m.types)}</div></div><div class="partyActions">${i?`<button data-lead="${i}">Make lead</button>`:'<button disabled>Lead</button>'}<button data-inspect-mon="${i}">Inspect</button></div></article>`).join('');openPanelHtml(panelShell('POKÉMON','Your Party',`${S.party.length}/${MAX_PARTY} Pokémon · extra captures go to Pokémon Center storage.`,`<div class="partyGrid">${cards}</div>`),{type:'party'});$$('[data-lead]',DOM.panelCard).forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.lead,m=S.party.splice(i,1)[0];S.party.unshift(m);saveGame();updateSideUI();openPartyPanel()});$$('[data-inspect-mon]',DOM.panelCard).forEach(btn=>btn.onclick=()=>openMonInspect(S.party[+btn.dataset.inspectMon],openPartyPanel))};

/* ------------------------------ New game ------------------------------- */
renderStarterChoices=function(){const starters=[['chikorita','Grass','A calm partner with strong defenses.'],['cyndaquil','Fire','Fast, direct, and excellent for early forests.'],['totodile','Water','A physical attacker that handles rocky routes well.']];DOM.starterChoices.innerHTML=starters.map(([id,role,desc])=>`<button class="starterChoice" data-starter="${id}"><img src="${spritePath(id)}"><b>${SPECIES[id].name}</b><span>${role} starter</span><small>${desc}</small></button>`).join('');$$('[data-starter]',DOM.starterChoices).forEach(btn=>btn.onclick=()=>selectStarter(btn.dataset.starter))};
startNewGame=function(){if(hasSave()&&!window.confirm('Begin a new Asterra adventure? Your current v90 save will be replaced after you choose a starter.'))return;S=classicFreshState();DOM.boot.classList.add('hidden');DOM.starterOverlay.classList.remove('hidden');renderStarterChoices()};
selectStarter=function(speciesId){S=classicFreshState();S.started=true;S.party=[createMon(speciesId,5,{starter:true,caughtAt:'seabreeze'})];S.lastTicker='The Asterra Gym Challenge begins in Seabreeze Town.';DOM.starterOverlay.classList.add('hidden');beginApp(false);AUDIO.playCry(speciesId);saveGame();showDialogue([{speaker:'PROFESSOR LINDEN',text:`Welcome to the ${CLASSIC_REGION_NAME} Region. ${SPECIES[speciesId].name} is your first partner.`},{speaker:'PROFESSOR LINDEN',text:'This is a traditional Pokémon journey: towns, routes, eight Gyms, trainer battles, caves, puzzles, TMs, HMs, Victory Road, the Elite Four, and a Champion.'},{speaker:'FIELD GUIDE',text:'Wild Pokémon appear only inside tall-grass patches. The species and levels available scale with your Gym Badges so high-BST Pokémon stay out of the early game.'},{speaker:'FIELD GUIDE',text:'Visit the lab once more for your Poké Balls and travel money, then follow the northern road to Route 1.'}])};
beginApp=function(resume){DOM.boot.classList.add('hidden');DOM.gameApp.classList.remove('hidden');S.currentArea=CLASSIC_AREAS[S.currentArea]?S.currentArea:'seabreeze';S.currentTitan=classicArea().theme;currentMap=mapCache[S.currentArea]||(mapCache[S.currentArea]=generateMap(S.currentArea));if(!resume||!walkableForMap(currentMap,S.player.x,S.player.y)){S.player.x=30;S.player.y=34}rebuildWildVisuals();updateSideUI();updateInteractionHint();AUDIO.startMusic('field')};
continueSavedGame=function(){if(!loadGame()){toast('The saved Asterra adventure could not be loaded.');return}beginApp(true);showAreaBanner()};
openPanelByName=function(name){if(B)return;if(name==='bag')openBagPanel();if(name==='party')openPartyPanel();if(name==='atlas')openAtlasPanel();if(name==='fieldnotes')openFieldNotesPanel()};

/* Repurpose the existing UI labels without changing its visual design. */
(function classicUiLabels(){
  const topLabel=document.querySelector('.brandBlock .miniLogo');if(topLabel)topLabel.textContent='DRIFTBOUND';
  const expeditionLabel=document.querySelector('.expeditionSection .sectionLabel');if(expeditionLabel)expeditionLabel.textContent='ACTIVE JOURNEY';
  const bondLabel=document.querySelector('.bondSection .sectionLabel');if(bondLabel)bondLabel.textContent='TRAINER RANK';
  const pulseLabel=document.querySelector('.pulseSection .sectionLabel');if(pulseLabel)pulseLabel.textContent='LOCAL WILD POKÉMON';
  const worldLabel=document.querySelector('.worldReadout small');if(worldLabel)worldLabel.textContent='GYM BADGES';
  const moneyHint=document.querySelector('.supplyBalance small');if(moneyHint)moneyHint.textContent='Spend at Poké Marts';
  const tickerLabel=document.querySelector('.migrationTicker span');if(tickerLabel)tickerLabel.textContent='REGION';
  const atlasBtn=document.querySelector('[data-panel="atlas"]');if(atlasBtn)atlasBtn.innerHTML='<span>◎</span>Town Map';
  const notesBtn=document.querySelector('[data-panel="fieldnotes"]');if(notesBtn)notesBtn.innerHTML='<span>▤</span>Pokédex';
  DOM.continueGame.classList.toggle('hidden',!hasSave());if(hasSave())DOM.newGame.textContent='New Adventure';else DOM.newGame.textContent='Begin Adventure';
})();

/* Expose useful v90 test hooks. */
window.__DRIFTBOUND_CLASSIC__={areas:CLASSIC_AREAS,gyms:GYMS,bst:classicBST,bstCap,canUseHM,enterArea:enterClassicArea,getState:()=>deepCopy(S)};
