/* -------------------------- Interactions / story ------------------------- */
function readClassicSign(o){showDialogue([{speaker:classicArea().name.toUpperCase(),text:o.type==='sign'?`${classicArea().subtitle}. Pokémon Centers heal your party for free; Poké Marts expand their stock as you earn badges.`:`The route continues toward ${o.target?CLASSIC_AREAS[o.target]?.name:'the next area'}.`}])}
function interactLab(){
  if(!S.storyFlags.lab){S.storyFlags.lab=true;S.inventory['Poke Ball']+=5;S.fieldCredits+=300;saveGame();showDialogue([{speaker:'PROFESSOR LINDEN',text:'Asterra is built around eight Gyms. Challenge them in order, explore every route, and reach the Pokémon League.'},{speaker:'PROFESSOR LINDEN',text:'Wild Pokémon gather in tall grass. Stronger species appear as your badge count rises, so the region opens naturally instead of throwing late-game Pokémon at you immediately.'},{speaker:'PROFESSOR LINDEN',text:'Take these five Poké Balls and ₽300. TMs teach battle moves; HMs unlock field techniques once you have the right Badge and a compatible Pokémon knows the move.'}]);updateSideUI();return}showDialogue([{speaker:'PROFESSOR LINDEN',text:'Your next objective is marked on the field display. Keep your team healthy and check the Town Map when you lose your bearings.'}])
}
function openCenterPanel(){const area=classicArea();openPanelHtml(panelShell('POKÉMON CENTER',area.name,'Heal, save, and manage your journey.',`<div class="decisionGrid"><button id="centerHeal" class="decisionCard"><b>Heal your party</b><small>Restore HP and PP for free.</small></button><button id="centerSave" class="decisionCard"><b>Save game</b><small>Make this Center your return point if you black out.</small></button><button id="centerPC" class="decisionCard"><b>Pokémon Storage</b><small>${S.storage.length} Pokémon currently in reserve.</small></button></div>`),{type:'center'});$('#centerHeal').onclick=()=>{healParty();S.lastCenter=S.currentArea;saveGame();updateSideUI();toast('Your Pokémon are fully healed.')};$('#centerSave').onclick=()=>{S.lastCenter=S.currentArea;saveGame(true)};$('#centerPC').onclick=()=>openStoragePanel()}
function openStoragePanel(){const cards=S.storage.map((m,i)=>`<button class="itemCard" data-withdraw="${i}" ${S.party.length>=MAX_PARTY?'disabled':''}><img src="${spritePath(m.species)}"><span><b>${m.name}</b><small>Lv.${m.level} · ${m.hp}/${m.maxHp} HP</small></span><span class="itemQty">WITHDRAW</span></button>`).join('')||'<p>No Pokémon are stored yet.</p>';openPanelHtml(panelShell('POKÉMON CENTER','Storage System','Extra captures are stored here.',`<div class="itemGrid">${cards}</div>`),{type:'storage'});$$('[data-withdraw]',DOM.panelCard).forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.withdraw;if(S.party.length>=MAX_PARTY)return;S.party.push(S.storage.splice(i,1)[0]);saveGame();openStoragePanel();updateSideUI()})}
const MART_PRICES={'Poke Ball':40,'Great Ball':120,'Ultra Ball':300,'Potion':60,'Super Potion':140,'Hyper Potion':320,'Revive':260};
function martStock(){const n=badgeCount(),stock=['Poke Ball','Potion'];if(n>=1)stock.push('Great Ball');if(n>=2)stock.push('Super Potion');if(n>=3)stock.push('Revive');if(n>=5)stock.push('Ultra Ball');if(n>=6)stock.push('Hyper Potion');return stock}
function openMartPanel(){const cards=martStock().map(name=>`<button class="itemCard" data-mart="${name}" ${S.fieldCredits<MART_PRICES[name]?'disabled':''}><img src="${itemIcon(name)}"><span><b>${name}</b><small>${ITEMS[name].desc}</small><small>Bag: ${S.inventory[name]||0}</small></span><span class="itemQty">₽ ${MART_PRICES[name]}</span></button>`).join('');openPanelHtml(panelShell('POKÉ MART',classicArea().name,`Money: ₽ ${S.fieldCredits}`,`<div class="itemGrid">${cards}</div>`),{type:'mart'});$$('[data-mart]',DOM.panelCard).forEach(btn=>btn.onclick=()=>{const name=btn.dataset.mart,price=MART_PRICES[name];if(S.fieldCredits<price)return;S.fieldCredits-=price;S.inventory[name]=(S.inventory[name]||0)+1;saveGame();updateSideUI();openMartPanel();toast(`${name} purchased.`)})}
function claimPickup(o){if(S.pickedItems[o.id])return;S.pickedItems[o.id]=true;if(o.type==='tmPickup'){S.tms[o.move]=(S.tms[o.move]||0)+1;toast(`${TM_NAMES[o.move]||MOVES[o.move].name} obtained.`)}else{S.inventory[o.item]=(S.inventory[o.item]||0)+(o.qty||1);toast(`${o.item} ×${o.qty||1} obtained.`)}mapCache[S.currentArea]=null;currentMap=generateMap(S.currentArea);saveGame();updateSideUI()}
function useHmGate(o){if(canUseHM(o.hm)){S.clearedObstacles[o.id]=true;mapCache[S.currentArea]=null;currentMap=generateMap(S.currentArea);rebuildWildVisuals();saveGame();showDialogue([{speaker:o.hm.toUpperCase(),text:`${S.party.find(m=>knowsMove(m,CLASSIC_HMS[o.hm].move))?.name||'Your Pokémon'} used ${o.hm}. The path is clear.`}]);return}const hm=CLASSIC_HMS[o.hm];const owned=S.hmsOwned[o.hm]?`You own ${o.hm}, but one of your party Pokémon must know the move.`:`You have not received HM ${o.hm} yet.`;showDialogue([{speaker:'FIELD OBSTACLE',text:`${owned} It becomes usable after Badge ${hm.badge}.`}])}
function togglePuzzle(o){S.puzzleState[S.currentArea]??={};S.puzzleState[S.currentArea][o.index]=!S.puzzleState[S.currentArea][o.index];mapCache[S.currentArea]=null;currentMap=generateMap(S.currentArea);saveGame();const solved=[0,1,2].every(i=>S.puzzleState[S.currentArea][i]);toast(solved?'The cave door opened.':'A mechanism shifted somewhere in the cave.')}

function classicTrainerBattle(o){if(S.defeatedTrainers[o.id]){showDialogue([{speaker:o.name.toUpperCase(),text:'Good battle. Keep going!'}]);return}startTrainerBattle(o.name,o.team,()=>{S.defeatedTrainers[o.id]=true;S.fieldCredits+=100+o.team.length*50;mapCache[S.currentArea]=null;currentMap=generateMap(S.currentArea);saveGame();updateSideUI();toast(`${o.name} defeated.`)})}
function startTrainerBattle(name,team,onComplete=null,index=0){if(index>=team.length){onComplete?.();return}const [species,level]=team[index],isGym=/^Leader /.test(name),isElite=/^(Elite Four|Champion)/.test(name);startBattle(species,{level,boss:false,trainer:true,gym:isGym,elite:isElite,noCapture:true,title:`${name} · ${index+1}/${team.length}`,onWin:()=>setTimeout(()=>startTrainerBattle(name,team,onComplete,index+1),260)})}

function openGymPanel(gymId){const gym=GYMS[gymId];if(!gym)return;if(S.badges[gymId]){showDialogue([{speaker:gym.leader.toUpperCase(),text:`You already earned the ${gym.badge}. Keep training for the League.`}]);return}if(badgeCount()<gym.index-1){showDialogue([{speaker:'GYM GUIDE',text:`This is Gym ${gym.index}. Earn the previous Badge before challenging ${gym.leader}.`}]);return}const progress=S.gymPuzzleProgress[gymId]||0;if(progress<gym.puzzle.length){const [prompt,options,answer]=gym.puzzle[progress];openPanelHtml(panelShell(`${gym.type.toUpperCase()} GYM`,`Gym Puzzle ${progress+1}/${gym.puzzle.length}`,prompt,`<div class="decisionGrid">${options.map((x,i)=>`<button class="decisionCard" data-gym-answer="${i}"><b>${escapeHtml(x)}</b></button>`).join('')}</div>`),{type:'gymPuzzle'});$$('[data-gym-answer]',DOM.panelCard).forEach(btn=>btn.onclick=()=>{if(+btn.dataset.gymAnswer===answer){S.gymPuzzleProgress[gymId]=progress+1;saveGame();openGymPanel(gymId)}else{S.gymPuzzleProgress[gymId]=0;toast('The mechanism reset. Try the puzzle again.');openGymPanel(gymId)}});return}openPanelHtml(panelShell(`${gym.type.toUpperCase()} GYM`,gym.leader,`Win to earn the ${gym.badge}.`,`<div class="decisionGrid"><button id="challengeLeader" class="decisionCard"><b>Challenge Gym Leader</b><small>${gym.team.map(([id,l])=>`${SPECIES[id].name} Lv.${l}`).join(' · ')}</small></button></div>`),{type:'gym'});$('#challengeLeader').onclick=()=>{closePanel();startTrainerBattle(gym.leader,gym.team,()=>awardGym(gymId))}}
function awardGym(gymId){const gym=GYMS[gymId];S.badges[gymId]=true;S.tms[gym.tm]=(S.tms[gym.tm]||0)+1;if(gym.hm)S.hmsOwned[gym.hm]=true;S.gymPuzzleProgress[gymId]=gym.puzzle.length;S.fieldCredits+=700+gym.index*250;saveGame();updateSideUI();showDialogue([{speaker:gym.leader.toUpperCase(),text:`You earned the ${gym.badge}! ${TM_NAMES[gym.tm]} was added to your Bag.${gym.hm?` You also received HM ${gym.hm}.`:''}`},{speaker:'GYM GUIDE',text:gym.hm?`HM ${gym.hm} can now be used in the field after you teach ${MOVES[CLASSIC_HMS[gym.hm].move].name} to a compatible party Pokémon.`:'All eight Badges open the road to Victory Road and the Pokémon League.'}])}

function startLeague(){if(badgeCount()<8){showDialogue([{speaker:'LEAGUE OFFICIAL',text:`You need all eight Asterra Gym Badges. You currently have ${badgeCount()}.`}]);return}if(S.champion){showDialogue([{speaker:'LEAGUE OFFICIAL',text:'Champion! The Hall of Fame remains open to you.'}]);return}const fights=[['Elite Four Rook',[['heracross',53],['scyther',54],['skarmory',55]]],['Elite Four Nyx',[['houndour',54],['sneasel',55],['gastly',55],['misdreavus',56]]],['Elite Four Coral',[['horsea',55],['psyduck',55],['totodile',56],['lapras',57]]],['Elite Four Orion',[['onix',56],['larvitar',57],['dratini',57],['dragonair',58]]],['Champion Kai',[['eevee',57],['pikachu',57],['lapras',58],['heracross',58],['skarmory',59],['dragonair',60]]]];const run=i=>{if(i>=fights.length){S.champion=true;S.storyFlags.league=true;saveGame();updateSideUI();openChampionPanel();return}startTrainerBattle(fights[i][0],fights[i][1],()=>setTimeout(()=>run(i+1),350))};run(0)}
function openChampionPanel(){openPanelHtml(panelShell('HALL OF FAME','Asterra Champion','You completed the traditional Gym Challenge.',`<div class="inspectStats"><h3>${escapeHtml(S.party[0]?.name||'Your team')} led the final victory.</h3><p>All towns, routes, caves, TMs, HMs and wild areas remain open after the credits.</p><div class="statRows"><div class="statRow">Gym Badges<b>8 / 8</b></div><div class="statRow">Trainers defeated<b>${Object.keys(S.defeatedTrainers).length}</b></div><div class="statRow">Pokémon caught<b>${Object.values(S.catches||{}).reduce((a,b)=>a+b,0)}</b></div><div class="statRow">TMs owned<b>${Object.values(S.tms||{}).reduce((a,b)=>a+b,0)}</b></div></div><button id="continueChampion" class="smallAction">Continue exploring</button></div>`,false),{closable:false,type:'ending'});$('#continueChampion').onclick=closePanel}

interactNearest=function(){if(inputLocked||B||activePanel)return;if(!DOM.dialogue.classList.contains('hidden')){advanceDialogue();return}const o=nearbyObject();if(!o){toast('There is nothing to interact with here.');return}if(o.type==='center')openCenterPanel();else if(o.type==='mart')openMartPanel();else if(o.type==='gym')openGymPanel(o.gym);else if(o.type==='lab')interactLab();else if(o.type==='trainer'||o.type==='rival')classicTrainerBattle(o);else if(o.type==='hmGate')useHmGate(o);else if(o.type==='puzzleSwitch')togglePuzzle(o);else if(o.type==='puzzleDoor')showDialogue([{speaker:'SEALED DOOR',text:'Three switches in this cave must all be active.'}]);else if(o.type==='itemPickup'||o.type==='tmPickup')claimPickup(o);else if(o.type==='leagueGate')startLeague();else if(o.type==='sign'||o.type==='exitSign')readClassicSign(o);else if(o.type==='wild')startBattle(o.species,{level:o.level||classicLevel()})};
