/* Pokemon Driftbound v121 - grounded meadow renderer reset. */
(function(){
'use strict';
const THREE=window.THREE,World=window.DriftboundWorld3D;if(!THREE||!World)return;
const prevRebuild=World.prototype.rebuild,prevRender=World.prototype.render,prevUpdate=World.prototype.updatePlayer,prevObstacle=World.prototype.makeObstacle;
const C={ground:'#58a94d',ground2:'#70bb59',grass:'#49a643',grass2:'#72c45b',trunk:'#674128',leaf:'#2d703b',leaf2:'#4a8d45',leaf3:'#68a34c',rock:'#74756d'};
const M=(color,o={})=>new THREE.MeshStandardMaterial(Object.assign({color,roughness:.94,metalness:0},o));
const exterior=m=>m&&!m.interior&&!m.roomKind;
const seeded=(w,s)=>w.seed(w.hash(s));
World.prototype.makeOcean=function(){this.ocean=null};
World.prototype.makeTitanIsland=function(){const ground=this.mesh(new THREE.PlaneGeometry(92,72),M(C.ground),{cast:false,receive:true});ground.name='V121_Mainland';ground.rotation.x=-Math.PI/2;ground.position.y=.30;this.worldRoot.add(ground)};
World.prototype.makeDistantScenery=function(){};
function tree(w,r,s=1){const g=new THREE.Group();g.name='V121_NaturalTree';const h=(3.8+r()*1.5)*s,tm=M(C.trunk);const trunk=w.mesh(new THREE.CylinderGeometry(.17*s,.27*s,h,9),tm);trunk.position.y=h/2;g.add(trunk);for(let i=0;i<3;i++){const a=i/3*Math.PI*2+r()*.3,b=w.mesh(new THREE.CylinderGeometry(.05*s,.1*s,1.15*s,7),tm);b.position.set(Math.cos(a)*.28*s,h*(.66+i*.07),Math.sin(a)*.28*s);b.rotation.z=1.12;b.rotation.y=a;g.add(b)}const mats=[M(C.leaf),M(C.leaf2),M(C.leaf3)],cy=h*.77;[[-.62,0,0,.9],[.62,.05,0,.92],[0,.55,0,1],[0,-.12,.62,.82],[0,.1,-.65,.84],[0,-.2,0,1.05]].forEach((v,i)=>{const q=w.mesh(new THREE.SphereGeometry(v[3]*s,12,8),mats[i%3]);q.position.set(v[0]*s,cy+v[1]*s,v[2]*s);q.scale.set(1.18,.72+r()*.14,1.02);g.add(q)});return g}
World.prototype.makeObstacle=function(t,p,r){if(t!=='verdant')return prevObstacle.call(this,t,p,r);const roll=r();if(roll<.72)return tree(this,r,.84+r()*.2);const g=new THREE.Group();g.name='V121_NaturalObstacle';if(roll<.88){const b=this.mesh(new THREE.SphereGeometry(.62,10,7),M(roll<.8?C.leaf:C.leaf2));b.scale.set(1.35,.65,1.05);b.position.y=.4;g.add(b)}else{const q=this.mesh(new THREE.IcosahedronGeometry(.56,1),M(C.rock));q.scale.set(1.25,.68,1);q.position.y=.34;g.add(q)}return g};
World.prototype.makeGrassPatch=function(t,p,r){const g=new THREE.Group();g.name='V121_GrassPatch',m=M(t==='verdant'?C.grass:p.ground2,{side:THREE.DoubleSide});for(let i=0;i<9;i++){const h=.26+r()*.32,b=this.mesh(new THREE.PlaneGeometry(.028,h),m,{cast:false,receive:true});b.position.set((r()-.5)*.62,h/2,(r()-.5)*.62);b.rotation.y=r()*Math.PI;b.rotation.z=(r()-.5)*.15;g.add(b)}return g};
function meadow(w,map){const r=seeded(w,'v121-meadow-'+(map.id||map.name||'')),a=[],b=[];for(let y=0;y<map.tiles.length;y++)for(let x=0;x<map.tiles[y].length;x++){const t=map.tiles[y][x];if(['ground','grass','rough','obstacle','edge'].includes(t))((x+y*3)%6<2?b:a).push([x,y])}const geo=new THREE.PlaneGeometry(1.08,1.08);geo.rotateX(-Math.PI/2);function add(list,color,name){if(!list.length)return;const im=new THREE.InstancedMesh(geo,M(color),list.length),d=new THREE.Object3D();im.name=name;im.receiveShadow=true;list.forEach(([x,y],i)=>{d.position.copy(w.gridPosition(x,y,.352));d.updateMatrix();im.setMatrixAt(i,d.matrix)});im.instanceMatrix.needsUpdate=true;w.worldRoot.add(im)}add(a,C.ground,'V121_MeadowTiles');add(b,C.ground2,'V121_MeadowTilesAlt');for(let i=0;i<14;i++){const p=w.mesh(new THREE.CircleGeometry(1.7+r()*2.8,18),M(C.grass2,{transparent:true,opacity:.16,depthWrite:false}),{cast:false,receive:false});p.rotation.x=-Math.PI/2;p.position.set((r()-.5)*54,.358,(r()-.5)*34);p.scale.set(1.2+r(),.7+r()*.5,1);w.worldRoot.add(p)}}
function grass(w,map){const r=seeded(w,'v121-grass-'+(map.id||map.name||'')),cells=[];for(let y=1;y<map.tiles.length-1;y++)for(let x=1;x<map.tiles[y].length-1;x++){const t=map.tiles[y][x];if(t==='grass')cells.push([x,y,13,1]);else if(t==='rough')cells.push([x,y,5,.55]);else if(t==='ground')cells.push([x,y,2,.3])}const max=6800,geo=new THREE.PlaneGeometry(.035,.64);geo.translate(0,.32,0);const im=new THREE.InstancedMesh(geo,M(C.grass,{side:THREE.DoubleSide}),max),d=new THREE.Object3D();im.name='V121_FieldGrass';let n=0;outer:for(const [x,y,count,min] of cells)for(let i=0;i<count;i++){if(n>=max)break outer;d.position.copy(w.gridPosition(x+(r()-.5)*.92,y+(r()-.5)*.92,.365));d.rotation.set(0,r()*Math.PI,(r()-.5)*.1);const sy=min+r()*(min>.9?.6:.25);d.scale.set(.7+r()*.5,sy,.8);d.updateMatrix();im.setMatrixAt(n++,d.matrix)}im.count=n;im.instanceMatrix.needsUpdate=true;w.worldRoot.add(im)}
function details(w,map){const r=seeded(w,'v121-detail-'+(map.id||map.name||'')),cells=[];for(let y=2;y<map.tiles.length-2;y++)for(let x=2;x<map.tiles[y].length-2;x++)if(['ground','grass','rough'].includes(map.tiles[y][x]))cells.push([x,y]);for(let i=0;i<Math.min(28,Math.floor(cells.length/40));i++){const [x,y]=cells[Math.floor(r()*cells.length)],q=w.mesh(new THREE.IcosahedronGeometry(.18+r()*.28,1),M(C.rock));q.name='V121_FieldRock';q.position.copy(w.gridPosition(x+(r()-.5)*.6,y+(r()-.5)*.6,.46));q.scale.set(1.3,.65+r()*.35,1);q.rotation.y=r()*Math.PI;w.worldRoot.add(q)}const colors=['#fff','#ffd75b','#f29bc0','#8fc9ff'];for(let i=0;i<Math.min(map.id==='willowmere'?140:90,Math.floor(cells.length*.18));i++){const [x,y]=cells[Math.floor(r()*cells.length)],p=w.gridPosition(x+(r()-.5)*.85,y+(r()-.5)*.85,.39),stem=w.mesh(new THREE.CylinderGeometry(.008,.011,.18,5),M('#3d783d'),{cast:false,receive:false});stem.position.copy(p);stem.position.y+=.09;w.worldRoot.add(stem);const col=colors[Math.floor(r()*colors.length)],fl=w.mesh(new THREE.SphereGeometry(.045,6,4),M(col,{emissive:col,emissiveIntensity:.02}),{cast:false,receive:false});fl.position.copy(p);fl.position.y+=.2;fl.scale.y=.4;w.worldRoot.add(fl)}}
function horizon(w,map){const r=seeded(w,'v121-horizon-'+(map.id||map.name||''));for(let i=0;i<12;i++){const a=i/12*Math.PI*2,h=w.mesh(new THREE.SphereGeometry(6+r()*3,16,9),M('#477f46'),{cast:false,receive:true});h.name='V121_DistantHill';h.scale.set(2+r(),.45+r()*.25,1.2);h.position.set(Math.cos(a)*(44+r()*7),1.4+r()*1.2,Math.sin(a)*(33+r()*6));w.worldRoot.add(h)}if(map.titanId==='verdant')for(let i=0;i<14;i++){const a=i/14*Math.PI*2,t=tree(w,r,.85+r()*.25);t.name='V121_HorizonTree';t.position.set(Math.cos(a)*(37+r()*6),.25,Math.sin(a)*(28+r()*5));w.worldRoot.add(t)}}
function finish(w,map){w.renderer.toneMapping=THREE.ACESFilmicToneMapping||THREE.ReinhardToneMapping;w.renderer.toneMappingExposure=1.1;w.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.45));w.scene.background=new THREE.Color(map.titanId==='verdant'?'#79bceb':'#9cc7d3');w.scene.fog=new THREE.Fog(map.titanId==='verdant'?'#b8d8bc':'#c6d9d4',35,112);w.camera.far=160;w.camera.updateProjectionMatrix();meadow(w,map);grass(w,map);details(w,map);horizon(w,map);const marker=new THREE.Object3D();marker.name='V121_WORLD_RESET_READY';w.worldRoot.add(marker)}
World.prototype.rebuild=function(map,titan,state){prevRebuild.call(this,map,titan,state);if(exterior(map))finish(this,map)};
World.prototype.render=function(time,ctx){if(ctx&&exterior(ctx.map)){const id=(ctx.map.id||ctx.map.name||ctx.map.titanId)+'|'+ctx.map.titanId;if(this.__v121Map!==id){this.__v121Map=id;this.buildKey=''}}return prevRender.call(this,time,ctx)};
World.prototype.updatePlayer=function(state,time,delta){prevUpdate.call(this,state,time,delta);if(this.navMap&&exterior(this.navMap)&&this.player){const g=this.player.position.clone().add(new THREE.Vector3(0,3.2,6.5));this.camera.position.lerp(g,1-Math.exp(-delta*6));const l=this.player.position.clone().add(new THREE.Vector3(0,.9,-4.2));this.cameraLook.lerp(l,1-Math.exp(-delta*7.5));this.camera.lookAt(this.cameraLook)}};
console.info('[Driftbound v121] mainland meadow renderer active.');
})();
