/* Pokémon: Driftbound v91 — higher fidelity buildings + instanced, wind-animated world. */
(function(){
  'use strict';
  const THREE=window.THREE,World=window.DriftboundWorld3D;if(!THREE||!World)return;
  const UNIT=1.05,COLS=60,ROWS=40;
  const V90_REBUILD=World.prototype.rebuild;
  const V90_MAKE_LANDMARK=World.prototype.makeLandmark;
  const V90_UPDATE_ANIMATIONS=World.prototype.updateAnimations;
  const V90_RENDER=World.prototype.render;

  function applyWindShader(mat,strength=.055,speed=1.7){
    mat.onBeforeCompile=shader=>{
      shader.uniforms.uV91Time={value:0};shader.uniforms.uV91Strength={value:strength};shader.uniforms.uV91Speed={value:speed};
      shader.vertexShader=shader.vertexShader.replace('#include <common>','#include <common>\nuniform float uV91Time;\nuniform float uV91Strength;\nuniform float uV91Speed;');
      shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>',`vec3 transformed = vec3(position);\n#ifdef USE_INSTANCING\n  vec3 v91Origin = vec3(instanceMatrix[3].xyz);\n#else\n  vec3 v91Origin = vec3(0.0);\n#endif\nfloat v91Height = clamp(position.y * 2.4, 0.0, 1.0);\nfloat v91Wave = sin(uV91Time*uV91Speed + v91Origin.x*1.17 + v91Origin.z*.83) + sin(uV91Time*.63 + v91Origin.z*1.41)*.35;\ntransformed.x += v91Wave*uV91Strength*v91Height;\ntransformed.z += cos(uV91Time*uV91Speed*.82 + v91Origin.x*.91)*uV91Strength*.38*v91Height;`);
      mat.userData.v91Shader=shader;
    };
    mat.customProgramCacheKey=()=>`v91wind-${strength}-${speed}`;return mat;
  }

  World.prototype.makeTerrainDetails=function(map,p){
    const rand=this.seed(this.hash(`v91-instanced-${map.areaId||map.titanId}`)),treeBiomes=new Set(['town','plains','forest','route','lake','coast','snow','graveyard']),trees=[],rocks=[],grassTiles=[];
    for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++){const tile=map.tiles[y]?.[x];if(tile==='obstacle'){if(treeBiomes.has(map.biome))trees.push([x,y,rand()]);else rocks.push([x,y,rand()]);}else if(tile==='grass')grassTiles.push([x,y]);}
    if(grassTiles.length){
      const perTile=map.biome==='forest'?10:8,count=grassTiles.length*perTile,geo=new THREE.PlaneGeometry(.065,.52,1,3);geo.translate(0,.26,0);
      const base=map.biome==='snow'?'#88b59a':map.biome==='graveyard'?'#536b58':map.biome==='coast'?'#62a359':'#438d4f';
      const mat=applyWindShader(new THREE.MeshStandardMaterial({color:base,roughness:.95,metalness:0,side:THREE.DoubleSide,vertexColors:true}),.075,map.biome==='coast'?2.15:1.75);
      const mesh=new THREE.InstancedMesh(geo,mat,count);mesh.castShadow=false;mesh.receiveShadow=true;const dummy=new THREE.Object3D(),color=new THREE.Color();let i=0;
      for(const [x,y] of grassTiles)for(let b=0;b<perTile;b++){const pos=this.gridPosition(x+(rand()-.5)*.82,y+(rand()-.5)*.82,.36);dummy.position.copy(pos);dummy.rotation.set((rand()-.5)*.04,rand()*Math.PI,(rand()-.5)*.13);dummy.scale.set(.78+rand()*.6,.72+rand()*.72,.78+rand()*.4);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);color.set(base).offsetHSL((rand()-.5)*.035,(rand()-.5)*.08,(rand()-.5)*.10);mesh.setColorAt(i,color);i++;}
      mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;this.worldRoot.add(mesh);
    }
    if(trees.length){
      const snow=map.biome==='snow',grave=map.biome==='graveyard',palm=map.biome==='coast';
      const trunkGeo=new THREE.CylinderGeometry(.13,.24,1.65,8,1),trunkMat=applyWindShader(new THREE.MeshStandardMaterial({color:grave?'#564b45':palm?'#8a694c':'#70513a',roughness:1}),.008,.95),trunks=new THREE.InstancedMesh(trunkGeo,trunkMat,trees.length);trunks.castShadow=true;trunks.receiveShadow=true;
      const crownCount=grave?trees.length:trees.length*(palm?6:5),crownGeo=palm?new THREE.ConeGeometry(.16,1.0,5):new THREE.IcosahedronGeometry(.54,1),crownMat=applyWindShader(new THREE.MeshStandardMaterial({color:snow?'#9dbeb1':grave?'#626662':'#3f8652',roughness:.92,vertexColors:true}),.035,1.0),crowns=new THREE.InstancedMesh(crownGeo,crownMat,crownCount);crowns.castShadow=false;crowns.receiveShadow=true;
      const dummy=new THREE.Object3D(),col=new THREE.Color();let ci=0;
      trees.forEach(([x,y,r],ti)=>{const base=this.gridPosition(x,y,.36),scale=.88+r*.28;dummy.position.set(base.x,base.y+.82*scale,base.z);dummy.rotation.set(0,r*Math.PI*2,(r-.5)*.035);dummy.scale.set(scale,scale,scale);dummy.updateMatrix();trunks.setMatrixAt(ti,dummy.matrix);
        if(grave){dummy.position.set(base.x,base.y+1.42*scale,base.z);dummy.rotation.set(0,r*Math.PI*2,0);dummy.scale.set(.48*scale,.22*scale,.48*scale);dummy.updateMatrix();crowns.setMatrixAt(ci,dummy.matrix);col.set('#5a625b');crowns.setColorAt(ci++,col);return;}
        if(palm){for(let k=0;k<6;k++){dummy.position.set(base.x,base.y+1.68*scale,base.z);dummy.rotation.set(0,k/6*Math.PI*2+r,0);dummy.rotation.z=Math.PI/2-.22;dummy.scale.set(.9*scale,.92*scale,.9*scale);dummy.updateMatrix();crowns.setMatrixAt(ci,dummy.matrix);col.set(k%2?'#3e8d58':'#55a66b');crowns.setColorAt(ci++,col);}return;}
        const offsets=[[0,1.65,0],[-.34,1.46,.03],[.34,1.45,.05],[-.17,1.75,-.18],[.2,1.73,.14]],palette=snow?['#aac9bd','#c8dbd3','#8fb1a3','#d9e7e1','#98baa9']:['#2f7046','#3f8652','#4b955b','#2d6b42','#579c61'];
        offsets.forEach((o,k)=>{dummy.position.set(base.x+o[0]*scale,base.y+o[1]*scale,base.z+o[2]*scale);dummy.rotation.set(0,r*Math.PI*2+k*.4,0);dummy.scale.set(scale*(.83+(k%2)*.12),scale*(.8+(k%3)*.08),scale*(.84+(k%2)*.08));dummy.updateMatrix();crowns.setMatrixAt(ci,dummy.matrix);col.set(palette[k%palette.length]);crowns.setColorAt(ci++,col);});
      });trunks.instanceMatrix.needsUpdate=true;crowns.instanceMatrix.needsUpdate=true;if(crowns.instanceColor)crowns.instanceColor.needsUpdate=true;this.worldRoot.add(trunks,crowns);
    }
    if(rocks.length){const geo=new THREE.DodecahedronGeometry(.48,0),mat=new THREE.MeshStandardMaterial({color:map.biome==='cave'?'#525965':'#6c655f',roughness:1}),mesh=new THREE.InstancedMesh(geo,mat,rocks.length);mesh.castShadow=true;mesh.receiveShadow=true;const dummy=new THREE.Object3D();rocks.forEach(([x,y,r],i)=>{const pos=this.gridPosition(x,y,.55);dummy.position.copy(pos);dummy.rotation.set(r*.35,r*Math.PI*2,r*.2);dummy.scale.set(.82+r*.45,.58+r*.65,.84+r*.35);dummy.updateMatrix();mesh.setMatrixAt(i,dummy.matrix);});mesh.instanceMatrix.needsUpdate=true;this.worldRoot.add(mesh);}
  };

  World.prototype.makeBuilding=function(kind,p){
    const g=new THREE.Group(),isCenter=kind==='center',isMart=kind==='mart',isGym=kind==='gym';const wallColor=isCenter?'#fbf7ee':isMart?'#eef7fb':isGym?'#f2efe5':'#eee6d7',trimColor=isCenter?'#d9494f':isMart?'#3278bb':isGym?p.accent:'#4f7c6c',roofColor=isCenter?'#db4d54':isMart?'#387fbe':isGym?p.accent:'#557d6d',W=isGym?8.8:7.4,D=isGym?6.0:5.2,H=isGym?4.4:3.8;
    const foundation=this.mesh(new THREE.BoxGeometry(W+.35,.3,D+.35),this.material('#d5cec1',{roughness:1}));foundation.position.y=.15;g.add(foundation);const wall=this.mesh(new THREE.BoxGeometry(W,H,D),this.material(wallColor,{roughness:.9}));wall.position.y=.3+H/2;g.add(wall);const lowerTrim=this.mesh(new THREE.BoxGeometry(W+.06,.32,D+.06),this.material(trimColor,{roughness:.82}));lowerTrim.position.y=.58;g.add(lowerTrim);const roof=this.mesh(new THREE.ConeGeometry(W*.72,1.65,4),this.material(roofColor,{roughness:.82}));roof.rotation.y=Math.PI/4;roof.scale.z=D/W*.95;roof.position.y=H+1.05;g.add(roof);
    const awning=this.mesh(new THREE.BoxGeometry(2.25,.16,.92),this.material(trimColor,{roughness:.72}));awning.position.set(0,2.25,D/2+.42);awning.rotation.x=-.12;g.add(awning);const door=this.mesh(new THREE.BoxGeometry(1.15,2.12,.13),this.material('#514238',{roughness:.7}));door.position.set(0,1.2,D/2+.075);g.add(door);const doorGlass=this.mesh(new THREE.BoxGeometry(.72,.92,.035),this.material('#8dc5d6',{emissive:'#376879',emissiveIntensity:.1,roughness:.22}),{cast:false,receive:false});doorGlass.position.set(0,1.5,D/2+.15);g.add(doorGlass);
    const winMat=this.material('#9ed8e5',{emissive:'#477b89',emissiveIntensity:.12,roughness:.25}),xs=isGym?[-3,-1.7,1.7,3]:[-2.45,2.45];xs.forEach(x=>{const frame=this.mesh(new THREE.BoxGeometry(1.55,1.28,.04),this.material(trimColor,{roughness:.75}),{cast:false,receive:false});frame.position.set(x,2.15,D/2+.025);g.add(frame);const w=this.mesh(new THREE.BoxGeometry(1.35,1.08,.08),winMat,{cast:false,receive:false});w.position.set(x,2.15,D/2+.11);g.add(w);});
    if(isCenter){const disc=this.mesh(new THREE.CylinderGeometry(.72,.72,.16,28),this.material('#f5f4ef'));disc.rotation.x=Math.PI/2;disc.position.set(0,3.45,D/2+.16);g.add(disc);const top=this.mesh(new THREE.BoxGeometry(1.24,.42,.06),this.material('#d94c52'),{cast:false,receive:false});top.position.set(0,3.64,D/2+.27);g.add(top);const band=this.mesh(new THREE.BoxGeometry(1.28,.12,.07),this.material('#34383d'),{cast:false,receive:false});band.position.set(0,3.45,D/2+.28);g.add(band);const dot=this.mesh(new THREE.CylinderGeometry(.12,.12,.07,18),this.material('#ffffff'),{cast:false,receive:false});dot.rotation.x=Math.PI/2;dot.position.set(0,3.45,D/2+.31);g.add(dot);}else{const text=this.makeTextPlane(isMart?'MART':isGym?'GYM':'LAB','#fff6cf');text.position.set(0,3.45,D/2+.19);text.scale.multiplyScalar(isGym?.62:.5);g.add(text);}g.traverse(o=>{if(o.isMesh&&o!==doorGlass){o.castShadow=true;o.receiveShadow=true;}});return g;
  };

  World.prototype.makeLandmark=function(o,titanId,p,state){
    if(['trainer','rival','elite','nurse','clerk','professor','gymGuide','gymLeader','npc'].includes(o.type)){const g=new THREE.Group();let color=o.color||'#4978a6',accent=o.accent||p.accent,female=!!o.female;if(o.type==='nurse'){color='#f0a1b0';accent='#ffffff';female=true;}if(o.type==='clerk'){color='#397cb6';accent='#f3d46e';}if(o.type==='professor'){color='#f2f0e8';accent='#5d7e9b';}if(o.type==='gymGuide'){color='#5d7cab';accent='#f1d26d';}if(o.type==='gymLeader'){color='#8c5b9e';accent=p.accent;}if(o.type==='npc'){color='#708d68';accent='#f1d26d';female=(o.x%2===1);}g.add(this.makeClassicTrainer(color,accent,female));const angles={up:0,down:Math.PI,left:Math.PI/2,right:-Math.PI/2};g.rotation.y=angles[o.dir||'down']??Math.PI;if(o.defeated){const bubble=this.makeTextPlane('✓','#d6f5d6');bubble.position.set(.28,1.65,0);bubble.scale.multiplyScalar(.22);g.add(bubble);}g.position.copy(this.gridPosition(o.x,o.y,.38));this.worldRoot.add(g);return;}
    if(o.type==='pc'){const g=new THREE.Group(),desk=this.mesh(new THREE.BoxGeometry(1.25,.75,.65),this.material('#d7d2c8'));desk.position.y=.38;g.add(desk);const screen=this.mesh(new THREE.BoxGeometry(.72,.5,.08),new THREE.MeshStandardMaterial({color:'#71c6df',emissive:'#3d95b0',emissiveIntensity:.55}));screen.position.set(0,.92,.05);g.add(screen);g.position.copy(this.gridPosition(o.x,o.y,.38));this.worldRoot.add(g);return;}
    if(o.type==='exitBuilding'){const rug=this.mesh(new THREE.BoxGeometry(2.0,.05,.78),new THREE.MeshStandardMaterial({color:'#d6c7a6',roughness:.9}),{cast:false,receive:true});rug.position.copy(this.gridPosition(o.x,o.y,.39));this.worldRoot.add(rug);return;}
    return V90_MAKE_LANDMARK.call(this,o,titanId,p,state);
  };

  World.prototype.rebuildClassicInterior=function(map,area,state){this.clearWorld();this.navMap=map;const kind=map.roomKind,p=area.palette||{accent:'#e4c969'},colors=kind==='center'?{floor:'#f4eee3',wall:'#f8f5ed',trim:'#d84d54'}:kind==='mart'?{floor:'#eaf2f4',wall:'#f5f8f7',trim:'#397fbd'}:kind==='gym'?{floor:'#e8e4d7',wall:'#f0eee7',trim:p.accent}:{floor:'#ddd8cc',wall:'#ede8dd',trim:'#5c806d'};this.scene.background=new THREE.Color('#243840');this.scene.fog=new THREE.Fog('#243840',25,58);const hemi=new THREE.HemisphereLight(0xf4fbff,0x51605d,.95);this.worldRoot.add(hemi);const key=new THREE.DirectionalLight(0xfff2d8,.85);key.position.set(-5,13,8);key.castShadow=true;key.shadow.mapSize.set(512,512);key.shadow.camera.left=-14;key.shadow.camera.right=14;key.shadow.camera.top=14;key.shadow.camera.bottom=-14;this.worldRoot.add(key);const roomCenter=this.gridPosition(30,21,.3),roomW=21*UNIT,roomD=22*UNIT,floor=this.mesh(new THREE.BoxGeometry(roomW,.28,roomD),this.material(colors.floor,{roughness:.88}),{cast:false,receive:true});floor.position.set(roomCenter.x,.15,roomCenter.z);this.worldRoot.add(floor);const wallMat=this.material(colors.wall,{roughness:.94}),trimMat=this.material(colors.trim,{roughness:.8}),back=this.mesh(new THREE.BoxGeometry(roomW,4.4,.35),wallMat);back.position.set(roomCenter.x,2.2,this.gridPosition(30,10).z);this.worldRoot.add(back);[-1,1].forEach(side=>{const w=this.mesh(new THREE.BoxGeometry(.35,4.4,roomD),wallMat);w.position.set(roomCenter.x+side*roomW/2,2.2,roomCenter.z);this.worldRoot.add(w);});const stripe=this.mesh(new THREE.BoxGeometry(roomW,.38,.08),trimMat,{cast:false,receive:false});stripe.position.set(roomCenter.x,2.65,this.gridPosition(30,10).z+.22);this.worldRoot.add(stripe);
    if(kind==='center'||kind==='mart'){const counter=this.mesh(new THREE.BoxGeometry(8.2,.9,1.1),trimMat);counter.position.set(roomCenter.x,.7,this.gridPosition(30,15).z);this.worldRoot.add(counter);if(kind==='center')for(let i=-2;i<=2;i++){const orb=this.mesh(new THREE.SphereGeometry(.18,14,8),new THREE.MeshStandardMaterial({color:i%2?'#f7f7f4':'#e45258',emissive:'#d04a50',emissiveIntensity:.18}));orb.position.set(roomCenter.x+i*.72,1.28,this.gridPosition(30,15).z);this.worldRoot.add(orb);}if(kind==='mart')for(let row=0;row<3;row++){const shelf=this.mesh(new THREE.BoxGeometry(3.4,.12,.55),this.material('#d7c296'));shelf.position.set(this.gridPosition(23,20).x,1+row*.65,this.gridPosition(23,20).z);this.worldRoot.add(shelf);}}
    else if(kind==='gym'){const ring=this.mesh(new THREE.CylinderGeometry(5.2,5.2,.09,40),this.material(colors.trim,{transparent:true,opacity:.18}),{cast:false,receive:true});ring.position.set(roomCenter.x,.36,this.gridPosition(30,20).z);this.worldRoot.add(ring);const edge=this.mesh(new THREE.TorusGeometry(5.2,.09,8,48),this.material(colors.trim));edge.rotation.x=Math.PI/2;edge.position.copy(ring.position);edge.position.y=.44;this.worldRoot.add(edge);}else for(const x of [24,30,36]){const table=this.mesh(new THREE.BoxGeometry(3.1,.72,1.25),this.material('#aa8c68'));table.position.set(this.gridPosition(x,18).x,.62,this.gridPosition(x,18).z);this.worldRoot.add(table);}map.objects.forEach(o=>this.makeLandmark(o,map.titanId,p,state));
  };

  World.prototype.rebuild=function(map,area,state){this.renderer.outputEncoding=THREE.sRGBEncoding;this.renderer.toneMapping=THREE.ACESFilmicToneMapping||THREE.LinearToneMapping;this.renderer.toneMappingExposure=.95;this.renderer.shadowMap.type=THREE.PCFShadowMap;if(map?.roomKind)return this.rebuildClassicInterior(map,area,state);V90_REBUILD.call(this,map,area,state);};
  World.prototype.updateAnimations=function(time){V90_UPDATE_ANIMATIONS.call(this,time);this.worldRoot.traverse(o=>{const s=o.material?.userData?.v91Shader;if(s?.uniforms?.uV91Time)s.uniforms.uV91Time.value=time*.001;});};
  World.prototype.render=function(time,args){V90_RENDER.call(this,time,args);if(!this.__v91Perf){this.__v91Perf={last:time,ema:16.7,next:time+1800,ratio:Math.min(window.devicePixelRatio||1,1.05)};this.renderer.setPixelRatio(this.__v91Perf.ratio);this.resize();return;}const p=this.__v91Perf,dt=Math.max(1,Math.min(80,time-p.last));p.last=time;p.ema=p.ema*.94+dt*.06;if(time>=p.next){p.next=time+1800;const fps=1000/p.ema;let ratio=p.ratio;if(fps<48)ratio=Math.max(.72,ratio-.1);else if(fps>57)ratio=Math.min(Math.min(window.devicePixelRatio||1,1.08),ratio+.05);if(Math.abs(ratio-p.ratio)>.001){p.ratio=ratio;this.renderer.setPixelRatio(ratio);this.resize();}}};
})();
